#!/bin/bash

# Define the name of the private key
KEY_NAME="school"

# Generate the key pair with the specified number of bits and passphrase
ssh-keygen -t rsa -b 4096 -f $KEY_NAME -N "betty"

# Output confirmation message
echo "RSA key pair created with name $KEY_NAME"
